config/routes.rb
Rails.application.routes.draw do
  resources :paper_sets
  devise_for :users
  resources :paper_gradeships
  resources :grades
  resources :papersubject_subjectships
  resources :question_paperships
  resources :writing_questions
  resources :selection_questions
  resources :subjects
  resources :papers do
    resources :questions
  end
  resources :paper_subjects
  resources :home
  resources :student_answer_logs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#management"
  post 'paper_subjects/:id', :to => 'paper_subjects#update'
  post 'papers/:id', :to => 'papers#update'
  post 'papers/:id/questions/:id', :to => 'questions#update'
  get  'homes/management', :to => 'home#management'
  get  'papers/tools/select', :to => 'papers#select'
  get  'papers/tools/show_papers', :to => 'papers#show_papers'
  get  'user_analytics', :to => 'user_analytics#index'
  get  'paper_analytics', :to => 'paper_analytics#index'
  get  'paper_set_buy_analytics', :to => 'paper_set_buy_analytics#index'

  # APIS
  get  'papers/api/get_paper_by_platform', :to => 'papers#get_paper_by_platform' 
  get  'papers/api/get_papers_by_subject', :to => 'papers#get_papers_by_subject' 
  get  'papers/api/get_papers_by_paper_set', :to => 'papers#get_papers_by_paper_set'
  get  'papers/api/get_papers_by_subject_and_grade', :to => 'papers#get_papers_by_subject_and_grade'  
  get  'questions/api/get_questionList_by_paperId', :to => 'questions#get_questionList_by_paperId'
  get  'questions/api/get_question_by_questionId', :to => 'questions#get_question_by_questionId'
  get  'grades/api/get_grades_by_platform', :to => 'grades#get_grades_by_platform'
  get  'subjects/api/get_subjects_by_grade', :to => 'subjects#get_subjects_by_grade' 
  get  'paper_sets/api/get_paper_sets_by_platform', :to => 'paper_sets#get_paper_sets_by_platform' 
  get  'paper_sets/api/get_paper_sets_by_id', :to => 'paper_sets#get_paper_sets_by_id' 
  get  'paper_sets/api/check_paper_bought', :to => 'paper_sets#check_paper_bought' 

  post 'homes/api/answer_question_logs', :to => 'home#answer_question_logs' 
  post 'homes/api/answer_question_correct', :to => 'home#answer_question_correct' 
  post 'homes/api/answer_question_correct_first', :to => 'home#answer_question_correct_first' 
  post 'homes/api/open_paper', :to => 'home#open_paper' 
  post 'homes/api/finish_paper', :to => 'home#finish_paper' 
  
  post 'homes/api/student_open_paper_log', :to => 'home#student_open_paper_log' 
  post 'homes/api/student_open_question_log', :to => 'home#student_open_question_log' 
  post 'homes/api/student_finish_paper', :to => 'home#student_finish_paper' 
  post 'homes/api/student_ask_teacher_question', :to => 'home#student_ask_teacher_question' 
  get 'homes/api/show_log_api_data', :to => 'home#show_log_api_data' 

  post 'papers/api/filter', :to => 'papers#filter'
  post 'paper_sets/api/clear_paper_paper_set_id', :to => 'paper_sets#clear_paper_paper_set_id'
  post 'paper_sets/api/student_buy_paper_set', :to => 'paper_sets#student_buy_paper_set'
  post 'paper_analytics/api/filter', :to => 'paper_analytics#filter'
  post 'user_analytics/api/filter', :to => 'user_analytics#filter'
  post 'paper_set_buy_analytics/api/filter', :to => 'paper_set_buy_analytics#filter'
  
end

app/models/papersubject_subjectship.rb
class PapersubjectSubjectship < ApplicationRecord
    belongs_to :subject , required: false
    belongs_to :paper_subject , required: false
end

app/controllers/papersubject_subjectships_controller.rb
class PapersubjectSubjectshipsController < ApplicationController
  before_action :set_papersubject_subjectship, only: [:show, :edit, :update, :destroy]

  # GET /papersubject_subjectships
  # GET /papersubject_subjectships.json
  def index
    @papersubject_subjectships = PapersubjectSubjectship.all
  end

  # GET /papersubject_subjectships/1
  # GET /papersubject_subjectships/1.json
  def show
  end

  # GET /papersubject_subjectships/new
  def new
    @papersubject_subjectship = PapersubjectSubjectship.new
  end

  # GET /papersubject_subjectships/1/edit
  def edit
  end

  # POST /papersubject_subjectships
  # POST /papersubject_subjectships.json
  def create
    @papersubject_subjectship = PapersubjectSubjectship.new(papersubject_subjectship_params)

    respond_to do |format|
      if @papersubject_subjectship.save
        format.html { redirect_to @papersubject_subjectship, notice: '試卷科目以成功建立' }
        format.json { render :show, status: :created, location: @papersubject_subjectship }
      else
        format.html { render :new }
        format.json { render json: @papersubject_subjectship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papersubject_subjectships/1
  # PATCH/PUT /papersubject_subjectships/1.json
  def update
    respond_to do |format|
      if @papersubject_subjectship.update(papersubject_subjectship_params)
        format.html { redirect_to @papersubject_subjectship, notice: '試卷科目以成功更新' }
        format.json { render :show, status: :ok, location: @papersubject_subjectship }
      else
        format.html { render :edit }
        format.json { render json: @papersubject_subjectship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papersubject_subjectships/1
  # DELETE /papersubject_subjectships/1.json
  def destroy
    @papersubject_subjectship.destroy
    respond_to do |format|
      format.html { redirect_to papersubject_subjectships_url, notice: '試卷科目以成功刪除' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_papersubject_subjectship
      @papersubject_subjectship = PapersubjectSubjectship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def papersubject_subjectship_params
      params.fetch(:papersubject_subjectship, {})
    end
end

app/helpers/papersubject_subjectships_helper.rb
module PapersubjectSubjectshipsHelper
end

app/views/papersubject_subjectships/_form.html.erb
<%= form_for(papersubject_subjectship) do |f| %>
  <% if papersubject_subjectship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(papersubject_subjectship.errors.count, "error") %> prohibited this papersubject_subjectship from being saved:</h2>

      <ul>
      <% papersubject_subjectship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papersubject_subjectships/edit.html.erb
<h1>Editing Papersubject Subjectship</h1>

<%= render 'form', papersubject_subjectship: @papersubject_subjectship %>

<%= link_to 'Show', @papersubject_subjectship %> |
<%= link_to 'Back', papersubject_subjectships_path %>

app/views/papersubject_subjectships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Papersubject Subjectships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papersubject_subjectships.each do |papersubject_subjectship| %>
      <tr>
        <td><%= link_to 'Show', papersubject_subjectship %></td>
        <td><%= link_to 'Edit', edit_papersubject_subjectship_path(papersubject_subjectship) %></td>
        <td><%= link_to 'Destroy', papersubject_subjectship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Papersubject Subjectship', new_papersubject_subjectship_path %>

app/views/papersubject_subjectships/new.html.erb
<h1>New Papersubject Subjectship</h1>

<%= render 'form', papersubject_subjectship: @papersubject_subjectship %>

<%= link_to 'Back', papersubject_subjectships_path %>

app/views/papersubject_subjectships/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_papersubject_subjectship_path(@papersubject_subjectship) %> |
<%= link_to 'Back', papersubject_subjectships_path %>