config/routes.rb
Rails.application.routes.draw do
  resources :paper_sets
  devise_for :users
  resources :paper_gradeships
  resources :grades
  resources :papersubject_subjectships
  resources :question_paperships
  resources :writing_questions
  resources :selection_questions
  resources :subjects
  resources :papers do
    resources :questions
  end
  resources :paper_subjects
  resources :home
  resources :student_answer_logs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#management"
  post 'paper_subjects/:id', :to => 'paper_subjects#update'
  post 'papers/:id', :to => 'papers#update'
  post 'papers/:id/questions/:id', :to => 'questions#update'
  get  'homes/management', :to => 'home#management'
  get  'papers/tools/select', :to => 'papers#select'
  get  'papers/tools/show_papers', :to => 'papers#show_papers'
  get  'user_analytics', :to => 'user_analytics#index'
  get  'paper_analytics', :to => 'paper_analytics#index'
  get  'paper_set_buy_analytics', :to => 'paper_set_buy_analytics#index'

  # APIS
  get  'papers/api/get_paper_by_platform', :to => 'papers#get_paper_by_platform' 
  get  'papers/api/get_papers_by_subject', :to => 'papers#get_papers_by_subject' 
  get  'papers/api/get_papers_by_paper_set', :to => 'papers#get_papers_by_paper_set'
  get  'papers/api/get_papers_by_subject_and_grade', :to => 'papers#get_papers_by_subject_and_grade'  
  get  'questions/api/get_questionList_by_paperId', :to => 'questions#get_questionList_by_paperId'
  get  'questions/api/get_question_by_questionId', :to => 'questions#get_question_by_questionId'
  get  'grades/api/get_grades_by_platform', :to => 'grades#get_grades_by_platform'
  get  'subjects/api/get_subjects_by_grade', :to => 'subjects#get_subjects_by_grade' 
  get  'paper_sets/api/get_paper_sets_by_platform', :to => 'paper_sets#get_paper_sets_by_platform' 
  get  'paper_sets/api/get_paper_sets_by_id', :to => 'paper_sets#get_paper_sets_by_id' 
  get  'paper_sets/api/check_paper_bought', :to => 'paper_sets#check_paper_bought' 

  post 'homes/api/answer_question_logs', :to => 'home#answer_question_logs' 
  post 'homes/api/answer_question_correct', :to => 'home#answer_question_correct' 
  post 'homes/api/answer_question_correct_first', :to => 'home#answer_question_correct_first' 
  post 'homes/api/open_paper', :to => 'home#open_paper' 
  post 'homes/api/finish_paper', :to => 'home#finish_paper' 
  
  post 'homes/api/student_open_paper_log', :to => 'home#student_open_paper_log' 
  post 'homes/api/student_open_question_log', :to => 'home#student_open_question_log' 
  post 'homes/api/student_finish_paper', :to => 'home#student_finish_paper' 
  post 'homes/api/student_ask_teacher_question', :to => 'home#student_ask_teacher_question' 
  get 'homes/api/show_log_api_data', :to => 'home#show_log_api_data' 

  post 'papers/api/filter', :to => 'papers#filter'
  post 'paper_sets/api/clear_paper_paper_set_id', :to => 'paper_sets#clear_paper_paper_set_id'
  post 'paper_sets/api/student_buy_paper_set', :to => 'paper_sets#student_buy_paper_set'
  post 'paper_analytics/api/filter', :to => 'paper_analytics#filter'
  post 'user_analytics/api/filter', :to => 'user_analytics#filter'
  post 'paper_set_buy_analytics/api/filter', :to => 'paper_set_buy_analytics#filter'
  
end

app/models/question_papership.rb
class QuestionPapership < ApplicationRecord 
end

app/controllers/question_paperships_controller.rb
class QuestionPapershipsController < ApplicationController
  before_action :set_question_papership, only: [:show, :edit, :update, :destroy]

  # GET /question_paperships
  # GET /question_paperships.json
  def index
    @question_paperships = QuestionPapership.all
  end

  # GET /question_paperships/1
  # GET /question_paperships/1.json
  def show
  end

  # GET /question_paperships/new
  def new
    @question_papership = QuestionPapership.new
  end

  # GET /question_paperships/1/edit
  def edit
  end

  # POST /question_paperships
  # POST /question_paperships.json
  def create
    @question_papership = QuestionPapership.new(question_papership_params)

    respond_to do |format|
      if @question_papership.save
        format.html { redirect_to @question_papership, notice: 'Question papership was successfully created.' }
        format.json { render :show, status: :created, location: @question_papership }
      else
        format.html { render :new }
        format.json { render json: @question_papership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_paperships/1
  # PATCH/PUT /question_paperships/1.json
  def update
    respond_to do |format|
      if @question_papership.update(question_papership_params)
        format.html { redirect_to @question_papership, notice: 'Question papership was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_papership }
      else
        format.html { render :edit }
        format.json { render json: @question_papership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_paperships/1
  # DELETE /question_paperships/1.json
  def destroy
    @question_papership.destroy
    respond_to do |format|
      format.html { redirect_to question_paperships_url, notice: 'Question papership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_papership
      @question_papership = QuestionPapership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_papership_params
      params.require(:question_papership).permit(:order)
    end
end

app/helpers/question_paperships_helper.rb
module QuestionPapershipsHelper
end

app/views/question_paperships/_form.html.erb
<%= form_for(question_papership) do |f| %>
  <% if question_papership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_papership.errors.count, "error") %> prohibited this question_papership from being saved:</h2>

      <ul>
      <% question_papership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order %>
    <%= f.number_field :order %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_paperships/edit.html.erb
<h1>Editing Question Papership</h1>

<%= render 'form', question_papership: @question_papership %>

<%= link_to 'Show', @question_papership %> |
<%= link_to 'Back', question_paperships_path %>

app/views/question_paperships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Paperships</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_paperships.each do |question_papership| %>
      <tr>
        <td><%= question_papership.order %></td>
        <td><%= link_to 'Show', question_papership %></td>
        <td><%= link_to 'Edit', edit_question_papership_path(question_papership) %></td>
        <td><%= link_to 'Destroy', question_papership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Papership', new_question_papership_path %>

app/views/question_paperships/new.html.erb
<h1>New Question Papership</h1>

<%= render 'form', question_papership: @question_papership %>

<%= link_to 'Back', question_paperships_path %>

app/views/question_paperships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @question_papership.order %>
</p>

<%= link_to 'Edit', edit_question_papership_path(@question_papership) %> |
<%= link_to 'Back', question_paperships_path %>