config/routes.rb
Rails.application.routes.draw do
  resources :paper_sets
  devise_for :users
  resources :paper_gradeships
  resources :grades
  resources :papersubject_subjectships
  resources :question_paperships
  resources :writing_questions
  resources :selection_questions
  resources :subjects
  resources :papers do
    resources :questions
  end
  resources :paper_subjects
  resources :home
  resources :student_answer_logs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#management"
  post 'paper_subjects/:id', :to => 'paper_subjects#update'
  post 'papers/:id', :to => 'papers#update'
  post 'papers/:id/questions/:id', :to => 'questions#update'
  get  'homes/management', :to => 'home#management'
  get  'papers/tools/select', :to => 'papers#select'
  get  'papers/tools/show_papers', :to => 'papers#show_papers'
  get  'user_analytics', :to => 'user_analytics#index'
  get  'paper_analytics', :to => 'paper_analytics#index'
  get  'paper_set_buy_analytics', :to => 'paper_set_buy_analytics#index'

  # APIS
  get  'papers/api/get_paper_by_platform', :to => 'papers#get_paper_by_platform' 
  get  'papers/api/get_papers_by_subject', :to => 'papers#get_papers_by_subject' 
  get  'papers/api/get_papers_by_paper_set', :to => 'papers#get_papers_by_paper_set'
  get  'papers/api/get_papers_by_subject_and_grade', :to => 'papers#get_papers_by_subject_and_grade'  
  get  'questions/api/get_questionList_by_paperId', :to => 'questions#get_questionList_by_paperId'
  get  'questions/api/get_question_by_questionId', :to => 'questions#get_question_by_questionId'
  get  'grades/api/get_grades_by_platform', :to => 'grades#get_grades_by_platform'
  get  'subjects/api/get_subjects_by_grade', :to => 'subjects#get_subjects_by_grade' 
  get  'paper_sets/api/get_paper_sets_by_platform', :to => 'paper_sets#get_paper_sets_by_platform' 
  get  'paper_sets/api/get_paper_sets_by_id', :to => 'paper_sets#get_paper_sets_by_id' 
  get  'paper_sets/api/check_paper_bought', :to => 'paper_sets#check_paper_bought' 

  post 'homes/api/answer_question_logs', :to => 'home#answer_question_logs' 
  post 'homes/api/answer_question_correct', :to => 'home#answer_question_correct' 
  post 'homes/api/answer_question_correct_first', :to => 'home#answer_question_correct_first' 
  post 'homes/api/open_paper', :to => 'home#open_paper' 
  post 'homes/api/finish_paper', :to => 'home#finish_paper' 
  
  post 'homes/api/student_open_paper_log', :to => 'home#student_open_paper_log' 
  post 'homes/api/student_open_question_log', :to => 'home#student_open_question_log' 
  post 'homes/api/student_finish_paper', :to => 'home#student_finish_paper' 
  post 'homes/api/student_ask_teacher_question', :to => 'home#student_ask_teacher_question' 
  get 'homes/api/show_log_api_data', :to => 'home#show_log_api_data' 

  post 'papers/api/filter', :to => 'papers#filter'
  post 'paper_sets/api/clear_paper_paper_set_id', :to => 'paper_sets#clear_paper_paper_set_id'
  post 'paper_sets/api/student_buy_paper_set', :to => 'paper_sets#student_buy_paper_set'
  post 'paper_analytics/api/filter', :to => 'paper_analytics#filter'
  post 'user_analytics/api/filter', :to => 'user_analytics#filter'
  post 'paper_set_buy_analytics/api/filter', :to => 'paper_set_buy_analytics#filter'
  
end

app/models/paper_set.rb
class PaperSet < ApplicationRecord
    has_many :papers
    has_many :student_buy_logs
    attr_accessor :paper_ids  
end

app/controllers/paper_sets_controller.rb
class PaperSetsController < ApplicationController
  before_action :set_paper_set, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except:[:student_buy_paper_set]
  # GET /paper_sets
  # GET /paper_sets.json
  def index

    platform_type = 0

    if current_user.has_role? :iAsk
      platform_type = 0
    elsif current_user.has_role? :udn
      platform_type = 1
    elsif current_user.has_role? :reader
      platform_type = 2
    elsif current_user.has_role? :admin
      platform_type = session[:platform_id]
    end


    orderParam = params[:orderParam]
    order = params[:order]
    if orderParam == nil
      orderParam = "id"
    end
    if order == nil
      order = "DESC"
    end

    if params[:relation] == "buy_logs"
      @paper_sets = PaperSet.left_joins(:student_buy_logs, :papers).group(:id).where("papers.platform_type = #{platform_type}").order("COUNT(student_buy_logs.id) #{order}")
    else
      @paper_sets = PaperSet.where(platform_type: platform_type).order("#{orderParam}  #{order}").paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /paper_sets/1
  # GET /paper_sets/1.json
  def show
  end

  # GET /paper_sets/new
  def new
    @paper_set = PaperSet.new
  end

  # GET /paper_sets/1/edit
  def edit
  end

  # POST /paper_sets
  # POST /paper_sets.json
  def create
    @paper_set = PaperSet.new(paper_set_params)
    if current_user.has_role? :iAsk
      @paper_set.platform_type = 0
    elsif current_user.has_role? :udn
      @paper_set.platform_type = 1  
    elsif current_user.has_role? :reader
      @paper_set.platform_type = 2
    elsif current_user.has_role? :admin
      @paper_set.platform_type = session[:platform_id]
    end
    
    respond_to do |format|
      if @paper_set.save   
        paper_ids = params[:paper_set][:papers].split(",")
        paper_ids.each{
          |paper_id|
          paper = Paper.find(paper_id)
          paper.update(:paper_set_id => @paper_set.id)
        }
        format.html { redirect_to paper_sets_path, notice: '成功建立試卷包' }
        format.json { render :index, status: :created, location: @paper_set }
      else
        format.html { render :new }
        format.json { render json: @paper_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paper_sets/1
  # PATCH/PUT /paper_sets/1.json
  def update
    respond_to do |format|
      if @paper_set.update(paper_set_params)
        paper_ids = params[:paper_set][:papers].split(",")
        paper_ids.each{
          |paper_id|
          paper = Paper.find(paper_id)
          paper.update(:paper_set_id => @paper_set.id)
        }
        format.html { redirect_to paper_sets_path, notice: '成功編輯試卷包' }
        format.json { render :index, status: :ok, location: @paper_set }
      else
        format.html { render :edit }
        format.json { render json: @paper_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paper_sets/1
  # DELETE /paper_sets/1.json
  def destroy
    @paper_set.destroy
    respond_to do |format|
      format.html { redirect_to paper_sets_url, notice: '成功刪除試卷包' }
      format.json { head :no_content }
    end
  end

  def get_paper_sets_by_platform
    @paper_sets = PaperSet.where(:platform_type => params[:platformId], :active => true)
    @paper_sets.each{
      |paper_set| 
      paper_ids = Paper.where(:paper_set_id => paper_set.id).pluck(:id)
      paper_set.assign_attributes({ :paper_ids => paper_ids})
    }

    render json: @paper_sets, methods: [:paper_ids]

  end

  def get_paper_sets_by_id
    @paper_set = PaperSet.find(params[:Id])
    paper_ids = Paper.where(:paper_set_id => @paper_set.id).pluck(:id)
    @paper_set.assign_attributes({ :paper_ids => paper_ids})

    render json: @paper_set, methods: [:paper_ids]
  end

  def clear_paper_paper_set_id
    paper_ids =  params[:paperIds]
    @papers = Paper.where(:id => paper_ids)
    @papers.each{
      |paper|
      paper.paper_set_id = nil
      paper.save!
    }

    render json: { result: true}
  end

  def student_buy_paper_set
    if StudentBuyLog.create(:student_id => params[:studentId], :paper_set_id => params[:paperSetId])
      render json: { result: true}
    else
      render json: { result: false}
    end
  end

  def check_paper_bought 
    @paper_set = StudentBuyLog.where(:paper_set_id => params[:paperSetId], :student_id => params[:studentId])  
    if @paper_set.present?
      render json: { bought: true }
    else
      render json: { bought: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper_set
      @paper_set = PaperSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_set_params
      params.require(:paper_set).permit(:title, :price, :public_date, :description, :active, :platform_type, :id, {:papers => []})
    end
end

app/helpers/paper_sets_helper.rb
module PaperSetsHelper
end

app/views/paper_sets/_form.html.erb
<%= simple_form_for(paper_set) do |f| %>
  <% if paper_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper_set.errors.count, "error") %> prohibited this paper_set from being saved:</h2>

      <ul>
      <% paper_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, label: '試卷包名稱' %>
  <div class="form-group string optional paper_set_title">
    <label class="control-label string optional" for="paper_set_title">包含試卷 (Id)</label></br>
    <input class="btn btn-default" id="select-paper" type="button" value="選擇試卷">
    <input class="form-control string optional" type="text" name="paper_set[papers]" id="paper_set_paper_id">
    <input id="delete-paper" class="btn btn-danger btn-sm" type="button" value="刪除試卷">
  </div>
  <%= f.input :price, label: '售價設定(點)' %>
  <%= f.input :public_date,as: :string, input_html: {type: :date}, label: '上架日期' %>
  <%= f.input :description, label: '描述' %>
  <% if paper_set.active != nil %>
    <%= f.input :active,:item_wrapper_class => 'inline', as: :radio_buttons, label: '有效性' %>
  <% else %>
    <%= f.input :active,:item_wrapper_class => 'inline',:checked => ['無效', false], as: :radio_buttons, label: '有效性' %>
  <% end %>  
  <%= f.input :id,as: :hidden %>  
  <%= f.button :submit , "送出", class: "btn btn-primary" %>
    <a href="/paper_sets"><button id="back" class= "btn btn-primary">上一頁</button></a>
<% end %>

<script>

var paperSetId = $("#paper_set_id").val();

if(localStorage.length!=0){
  $("#paper_set_paper_id").val(localStorage.paperIds)
  $("#paper_set_title").val(localStorage.paperSetTitle)
  $("#paper_set_price").val(localStorage.paperSetPrice)
  $("#paper_set_public_date").val(localStorage.paperSetPublicDate)
  $("#paper_set_description").val(localStorage.paperSetDescription)
  if(localStorage.paperSetActive){
    $("#paper_set_active_true").attr("checked", true)
  }
  else{
    $("#paper_set_active_true").attr("checked", false)
  }
}
else{
  loadPapers();
}

$("#select-paper").on("click", function(){
  var paperSetTitle = $("#paper_set_title").val();
  var paperSetPrice = $("#paper_set_price").val();
  var paperSetPublicDate = $("#paper_set_public_date").val();
  var paperSetDescription = $("#paper_set_description").val();
  var paperSetActive = $(".paper_set_active input:checked").val();

  localStorage.setItem("paperSetTitle", paperSetTitle);
  localStorage.setItem("paperSetPrice", paperSetPrice);
  localStorage.setItem("paperSetPublicDate", paperSetPublicDate);
  localStorage.setItem("paperSetDescription", paperSetDescription);
  localStorage.setItem("paperSetActive", paperSetActive);
  localStorage.setItem("paperSetId", paperSetId);    

  window.open("/papers/tools/select?id="+paperSetId,"","width=1200,height=600")

})

$('.simple_form').submit(function() {
  localStorage.clear();
});
$('#back').on("click",function() {
  localStorage.clear();
});
$('#delete-paper').on("click", function(){
  var paperIds = $("#paper_set_paper_id").val().split(",");
  deletePapers(paperIds);
})

function loadPapers(){
  $.ajax({
    type: "GET",
    url: "/paper_sets/api/get_paper_sets_by_id.json?Id="+paperSetId,
    dataType: "json",
    contentType: 'application/json',
    data: {}
    })
    .complete(function(data){
     var paperIds = data.responseJSON.paper_ids
     $("#paper_set_paper_id").val(paperIds)
    });
}

function deletePapers( paperIds ){
  $.ajax({
      type: "post",
      url: "/paper_sets/api/clear_paper_paper_set_id",
      data: {paperIds : paperIds}
    })
    .complete(function(data){
      window.location.reload();
    });
}
</script>

app/views/paper_sets/edit.html.erb
<h1>編輯試卷包</h1>

<%= render 'form', paper_set: @paper_set %>

app/views/paper_sets/index.html.erb
<p id="notice"><%= notice %></p>

<script>

$(function(){
  $("#batch-active").click(function(){
    var paper_set_ids = []
    var count = 0
    var active = true
    $(".paper_set_id:checked").each(function(){
      paper_set_ids.push($(this).val());
    });
    ajaxBatchUpdate(paper_set_ids,active,count)
  });
  $("#batch-inactive").click(function(){
    var paper_set_ids = []
    var count = 0
    var active = false
    $(".paper_set_id:checked").each(function(){
      paper_set_ids.push($(this).val());
    });
    ajaxBatchUpdate(paper_set_ids,active,count)
  });
  $("#check-all").click(function(){
    $(".paper_set_id").each(function(){
      $(this).attr("checked","checked")
    });
  })
  function ajaxBatchUpdate(paper_set_ids,active,count){
    $.ajax({
        type: "POST",
        url: "/paper_sets/"+paper_set_ids[count],
        dataType: "script",
        contentType: 'application/json',
        data: JSON.stringify({ active:active, _method:'put' })
        })
        .complete(function(data){
          if(count< paper_set_ids.length-1){
            count += 1;
            ajaxBatchUpdate(paper_set_ids,active,count);
          }
        })
        }
})

</script> 

<h1>試卷包管理</h1>
<button class="btn btn-primary"><%= link_to '新增試卷包', new_paper_set_path %></button>
<button class="btn btn-success" id="batch-active">批次有效</button>
<button class="btn btn-danger" id="batch-inactive">批次無效</button>
<table class="table">
  <thead>
    <tr class="thead">
      <th><button class="btn btn-info" id="check-all">全選</button></th>
      <th>試卷包名稱&nbsp;
        <a class="sorter" id="name-ASC" href="/paper_sets?orderParam=title&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/paper_sets?orderParam=title&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th>售價設定(點)&nbsp;
        <a class="sorter" id="name-ASC" href="/paper_sets?orderParam=price&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/paper_sets?orderParam=price&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th>上架日期&nbsp;
        <a class="sorter" id="name-ASC" href="/paper_sets?orderParam=public_date&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/paper_sets?orderParam=public_date&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th>描述&nbsp;
        <a class="sorter" id="name-ASC" href="/paper_sets?orderParam=description&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/paper_sets?orderParam=description&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th>有效性&nbsp;
        <a class="sorter" id="name-ASC" href="/paper_sets?orderParam=active&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/paper_sets?orderParam=active&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th>購買次數&nbsp;
        <a class="sorter" id="name-ASC" href="/paper_sets?relation=buy_logs&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/paper_sets?relation=buy_logs&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th colspan="3">
      </th>
    </tr>
  </thead>

  <tbody>
    <% @paper_sets.each do |paper_set| %>
      <tr>
        <td><input type="checkbox" class="paper_set_id" value=<%= paper_set.id %>></td>
        <td><span class="column-name"><%= paper_set.title %></span></td>
        <td><span class="column-name"><%= paper_set.price %></span></td>
        <td><span class="column-name"><%= paper_set.public_date %></span></td>
        <td><span class="column-name"><%= paper_set.description %></span></td>
        <td>
          <% if paper_set.active == true%>
          <span class="active">已啟用</span>
          <% else %>
          <span class="inactive">未啟用</span>
          <% end %>
        </td>
        <td><span class="column-name"><%= paper_set.student_buy_logs.size %></span></td>
        <td><%= link_to '編輯', edit_paper_set_path(paper_set) %></td>
        <td><%= link_to '刪除', paper_set, method: :delete, data: { confirm: '您確定嗎?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @paper_sets, :previous_label => '上一頁', :next_label => '下一頁' %>

app/views/paper_sets/new.html.erb
<h1>新增試卷包</h1>

<%= render 'form', paper_set: @paper_set %>

app/views/paper_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper_set.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @paper_set.price %>
</p>

<p>
  <strong>Public date:</strong>
  <%= @paper_set.public_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @paper_set.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @paper_set.active %>
</p>

<%= link_to 'Edit', edit_paper_set_path(@paper_set) %> |
<%= link_to 'Back', paper_sets_path %>