config/routes.rb
Rails.application.routes.draw do
  resources :paper_sets
  devise_for :users
  resources :paper_gradeships
  resources :grades
  resources :papersubject_subjectships
  resources :question_paperships
  resources :writing_questions
  resources :selection_questions
  resources :subjects
  resources :papers do
    resources :questions
  end
  resources :paper_subjects
  resources :home
  resources :student_answer_logs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#management"
  post 'paper_subjects/:id', :to => 'paper_subjects#update'
  post 'papers/:id', :to => 'papers#update'
  post 'papers/:id/questions/:id', :to => 'questions#update'
  get  'homes/management', :to => 'home#management'
  get  'papers/tools/select', :to => 'papers#select'
  get  'papers/tools/show_papers', :to => 'papers#show_papers'
  get  'user_analytics', :to => 'user_analytics#index'
  get  'paper_analytics', :to => 'paper_analytics#index'
  get  'paper_set_buy_analytics', :to => 'paper_set_buy_analytics#index'

  # APIS
  get  'papers/api/get_paper_by_platform', :to => 'papers#get_paper_by_platform' 
  get  'papers/api/get_papers_by_subject', :to => 'papers#get_papers_by_subject' 
  get  'papers/api/get_papers_by_paper_set', :to => 'papers#get_papers_by_paper_set'
  get  'papers/api/get_papers_by_subject_and_grade', :to => 'papers#get_papers_by_subject_and_grade'  
  get  'questions/api/get_questionList_by_paperId', :to => 'questions#get_questionList_by_paperId'
  get  'questions/api/get_question_by_questionId', :to => 'questions#get_question_by_questionId'
  get  'grades/api/get_grades_by_platform', :to => 'grades#get_grades_by_platform'
  get  'subjects/api/get_subjects_by_grade', :to => 'subjects#get_subjects_by_grade' 
  get  'paper_sets/api/get_paper_sets_by_platform', :to => 'paper_sets#get_paper_sets_by_platform' 
  get  'paper_sets/api/get_paper_sets_by_id', :to => 'paper_sets#get_paper_sets_by_id' 
  get  'paper_sets/api/check_paper_bought', :to => 'paper_sets#check_paper_bought' 

  post 'homes/api/answer_question_logs', :to => 'home#answer_question_logs' 
  post 'homes/api/answer_question_correct', :to => 'home#answer_question_correct' 
  post 'homes/api/answer_question_correct_first', :to => 'home#answer_question_correct_first' 
  post 'homes/api/open_paper', :to => 'home#open_paper' 
  post 'homes/api/finish_paper', :to => 'home#finish_paper' 
  
  post 'homes/api/student_open_paper_log', :to => 'home#student_open_paper_log' 
  post 'homes/api/student_open_question_log', :to => 'home#student_open_question_log' 
  post 'homes/api/student_finish_paper', :to => 'home#student_finish_paper' 
  post 'homes/api/student_ask_teacher_question', :to => 'home#student_ask_teacher_question' 
  get 'homes/api/show_log_api_data', :to => 'home#show_log_api_data' 

  post 'papers/api/filter', :to => 'papers#filter'
  post 'paper_sets/api/clear_paper_paper_set_id', :to => 'paper_sets#clear_paper_paper_set_id'
  post 'paper_sets/api/student_buy_paper_set', :to => 'paper_sets#student_buy_paper_set'
  post 'paper_analytics/api/filter', :to => 'paper_analytics#filter'
  post 'user_analytics/api/filter', :to => 'user_analytics#filter'
  post 'paper_set_buy_analytics/api/filter', :to => 'paper_set_buy_analytics#filter'
  
end

app/models/paper.rb
class Paper < ApplicationRecord

    attr_accessor :subject_name
    has_many :questions
    has_many :student_paper_logs
    has_many :student_open_paper_logs
    has_many :paper_gradeships
    belongs_to :paper_set
    has_many :grades, :through => :paper_gradeships
    has_many :students, :through => :student_paper_logs
    belongs_to :paper_subject, class_name: "PaperSubject", foreign_key: "paper_subject_id"
    accepts_nested_attributes_for :paper_gradeships
    accepts_nested_attributes_for :student_paper_logs

    
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  before_action :set_paper, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :filter

  # GET /papers
  # GET /papers.json
  def index

    if current_user.has_role? :iAsk
      session[:platform_id] = 0
    elsif current_user.has_role? :udn
      session[:platform_id] = 1
    elsif current_user.has_role? :reader
      session[:platform_id] = 2
    end


    if params[:filter] == nil
      orderParam = params[:orderParam]
      order = params[:order]
      
      if orderParam == nil
        orderParam = "id"
      end
      if order == nil
        order = "DESC"
      end

      if params[:relation] == "paper_subjects"
        @papers = Paper.includes(:paper_subject).where(platform_type: session[:platform_id]).order("paper_subjects.title  #{order}").paginate(:page => params[:page], :per_page => 10)
      elsif params[:relation] == "grades"
        @papers = Paper.includes(:grades).where(platform_type: session[:platform_id]).order("grades.name  #{order}").paginate(:page => params[:page], :per_page => 10)
      else
        @papers = Paper.where(platform_type: session[:platform_id]).order("#{orderParam}  #{order}").paginate(:page => params[:page], :per_page => 10)
      end
    else
      @papers = Paper.where(:id => session[:filter_papers_id], :platform_type => session[:platform_id]).paginate(:page => params[:page], :per_page => 10)
    end
    @question = Question.new
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new

    if current_user.has_role? :iAsk
      @grades = Grade.where(platform_type: 0)
    elsif current_user.has_role? :udn
      @grades = Grade.where(platform_type: 1) 
    elsif current_user.has_role? :reader
      @grades = Grade.where(platform_type: 2)
    elsif current_user.has_role? :admin
      @grades = Grade.where(platform_type: session[:platform_id])
    end

    if current_user.has_role? :iAsk
      @paper_subjects = PaperSubject.where(platform_type: 0)
    elsif current_user.has_role? :udn
      @paper_subjects = PaperSubject.where(platform_type: 1) 
    elsif current_user.has_role? :reader
      @paper_subjects = PaperSubject.where(platform_type: 2)
    elsif current_user.has_role? :admin
      @paper_subjects = PaperSubject.where(platform_type: session[:platform_id])
    end

    @visibles = [{name: "免費可見"},{name: "購點後可見"},{name: "付費可見"}]
  end

  # GET /papers/1/edit
  def edit
    if current_user.has_role? :iAsk
      @grades = Grade.where(platform_type: 0)
    elsif current_user.has_role? :udn
      @grades = Grade.where(platform_type: 1) 
    elsif current_user.has_role? :reader
      @grades = Grade.where(platform_type: 2)
    elsif current_user.has_role? :admin
      @grades = Grade.where(platform_type: session[:platform_id])
    end

    if current_user.has_role? :iAsk
      @paper_subjects = PaperSubject.where(platform_type: 0)
    elsif current_user.has_role? :udn
      @paper_subjects = PaperSubject.where(platform_type: 1) 
    elsif current_user.has_role? :reader
      @paper_subjects = PaperSubject.where(platform_type: 2)
    elsif current_user.has_role? :admin
      @paper_subjects = PaperSubject.where(platform_type: session[:platform_id])
    end
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)
    if current_user.has_role? :iAsk
      @paper.platform_type = 0
    elsif current_user.has_role? :udn
      @paper.platform_type = 1  
    elsif current_user.has_role? :reader
      @paper.platform_type = 2
    elsif current_user.has_role? :admin
      @paper.platform_type = session[:platform_id]
    end
    respond_to do |format|
      if @paper.save
        format.html { redirect_to papers_path, notice: '成功建立試卷' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to papers_path, notice: '成功編輯試卷' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: '成功刪除試卷' }
      format.json { head :no_content }
    end
  end

  def get_public_date
    @papers = Paper.distinct(:public_date).where(:platform_type => params[:platformId])
    render @papers
  end
  
  def get_paper_by_platform
    @papers = Paper.select("papers.id,papers.title,papers.public_date,papers.paper_subject_id,papers.visible, papers.paper_set_id, paper_subjects.title_view, paper_subjects.id as paper_subject_id").joins("LEFT JOIN paper_subjects ON papers.paper_subject_id = paper_subjects.id ").where(:active => true,:platform_type => params[:platformId])
    paper_subject_ids = Paper.distinct(:paper_subject_id).where(:active => true, :platform_type => params[:platformId]).pluck(:paper_subject_id)
    @papers.each{
      |paper| 
      subject_name_list = PaperSubject.find(paper.paper_subject_id).subjects.pluck(:name).join(",")
      correct_rates = StudentCorrectRate.where(:paper_id => paper.id, :student_id => params[:studentId]).pluck(:correct_rate)
      if !correct_rates.present?
        correct_rate = 0
      else
        correct_rate = correct_rates[0].to_i
      end

      question_ids =  Question.where(:paper_id => paper.id, :active => true).where.not(:question_type => "非選").pluck(:id)
      total_q_size = question_ids.size
      log_ids = StudentAnswerLog.where(:question_id => question_ids , :student_id => params[:studentId]).pluck(:question_id)
      answered_size = log_ids.uniq.size

      if total_q_size == 0
        finish_rate = 0
      else
        finish_rate = (answered_size.to_f / total_q_size.to_f)*100
      end


      paper.assign_attributes({ :subject_name => subject_name_list})
      paper.assign_attributes({ :correct_rate => correct_rate})
      paper.assign_attributes({ :finish_rate => finish_rate})      
    }
    render json: @papers, methods: [:subject_name, :correct_rate, :finish_rate]
  end

  def get_papers_by_subject
    paper_subject_ids = PapersubjectSubjectship.where(:subject_id => params[:subjectId]).pluck(:paper_subject_id)
    @papers = Paper.select("papers.id,papers.title,papers.public_date,papers.paper_subject_id,papers.visible,papers.paper_set_id, paper_subjects.title_view, paper_subjects.id as paper_subject_id").joins("LEFT JOIN paper_subjects ON papers.paper_subject_id = paper_subjects.id ").where(:paper_subject_id => paper_subject_ids, :active => true)
    @papers.each{
      |paper| 
      subject_name_list = PaperSubject.find(paper.paper_subject_id).subjects.pluck(:name).join(",")
      correct_rates = StudentCorrectRate.where(:paper_id => paper.id, :student_id => params[:studentId]).pluck(:correct_rate)
      if !correct_rates.present?
        correct_rate = 0
      else
        correct_rate = correct_rates[0].to_i
      end

      question_ids =  Question.where(:paper_id => paper.id, :active => true).where.not(:question_type => "非選").pluck(:id)
      total_q_size = question_ids.size
      log_ids = StudentAnswerLog.where(:question_id => question_ids , :student_id => params[:studentId]).pluck(:question_id)
      answered_size = log_ids.uniq.size

      if total_q_size == 0
        finish_rate = 0
      else
        finish_rate = (answered_size.to_f / total_q_size.to_f)*100
      end

      paper.assign_attributes({ :subject_name => subject_name_list})
      paper.assign_attributes({ :correct_rate => correct_rate})
      paper.assign_attributes({ :finish_rate => finish_rate})     
    }
    render json: @papers, methods: [:subject_name, :correct_rate]

  end

  def get_papers_by_subject_and_grade
    @papers = Paper.joins(:grades).where("grades.id = #{params[:gradeId]}")
    paper_subject_ids = PapersubjectSubjectship.where(:subject_id => params[:subjectId]).pluck(:paper_subject_id)
    @papers = @papers.select("papers.id,papers.title,papers.public_date,papers.paper_subject_id,papers.visible,papers.paper_set_id, paper_subjects.title_view, paper_subjects.id as paper_subject_id").joins("LEFT JOIN paper_subjects ON papers.paper_subject_id = paper_subjects.id ").where(:paper_subject_id => paper_subject_ids, :active => true)
    @papers.each{
      |paper| 
      subject_name_list = PaperSubject.find(paper.paper_subject_id).subjects.pluck(:name).join(",")
      correct_rates = StudentCorrectRate.where(:paper_id => paper.id, :student_id => params[:studentId]).pluck(:correct_rate)
      if !correct_rates.present?
        correct_rate = 0
      else
        correct_rate = correct_rates[0].to_i
      end

      question_ids =  Question.where(:paper_id => paper.id, :active => true).where.not(:question_type => "非選").pluck(:id)
      total_q_size = question_ids.size
      log_ids = StudentAnswerLog.where(:question_id => question_ids , :student_id => params[:studentId]).pluck(:question_id)
      answered_size = log_ids.uniq.size

      if total_q_size == 0
        finish_rate = 0
      else
        finish_rate = (answered_size.to_f / total_q_size.to_f)*100
      end

      paper.assign_attributes({ :subject_name => subject_name_list})
      paper.assign_attributes({ :correct_rate => correct_rate})
      paper.assign_attributes({ :finish_rate => finish_rate})     
    }
    render json: @papers, methods: [:subject_name, :correct_rate]
  end


  def get_papers_by_paper_set
    @papers = Paper.where(:paper_set_id => params[:paperSetId], :active => true)

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_filters.html.erb
<script>
$(function(){
    var pathName =  window.location.pathname
    $("#pathName").val(pathName)

    var url_string = window.location.href
    var url = new URL(url_string);
    var id = url.searchParams.get("id");
    $("#paperSetId").val(id)
})
</script>

<form id="filter" action="/papers/api/filter" novalidate="novalidate" method="post">
科目 : <%= collection_select(:filter, :subject_name, Subject.select(:name).distinct.where(:platform_type => session[:platform_id]).order(:name), :name, :name, prompt: true) %>
年級 : <%= collection_select(:filter, :grade_name, Grade.select(:name).distinct.where(:platform_type => session[:platform_id]).order(:name), :name, :name, prompt: true) %>
上架日期: 
<%= collection_select(:filter, :init_public_date, Paper.select(:public_date).distinct.where(:platform_type => session[:platform_id]).order(:public_date), :public_date, :public_date, prompt: true) %>
~
<%= collection_select(:filter, :end_public_date, Paper.select(:public_date).distinct.where(:platform_type => session[:platform_id]).order(:public_date), :public_date, :public_date, prompt: true) %>
有效性:
<select name="filter[active]">
    <option value="">請選擇</option>
    <option value="true">有效</option>
    <option value="false">無效</option>
</select>
<input id='pathName' name="filter[path_name]" type="hidden">
<input id='paperSetId' name="filter[paper_set_id]" type="hidden">
<button type="submit">
篩選
</button>
<a href="/papers" class="btn btn-default">重設</a>
</form>

app/views/papers/_form.html.erb
<%= simple_form_for(paper) do |f| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper_subject from being saved:</h2>

      <ul>
      <% paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.input :title, label: '試卷名稱' %>
  <div class="form-group string optional grade">
    <label class="control-label string optional" for="grade">年級</label><br>
      <% @grades.each do |g| %>
        <%= check_box_tag :grade_ids,g.id, f.object.grades.include?(g), :name => "paper[grade_ids][]",class:"boolean optional" %>
        <%= g.name %>
      <% end %>
  </div>
  <%= f.input :paper_subject_id, :collection => @paper_subjects,:value_method => :id,:label_method => :title,:label => "試卷科目", :include_blank => false %>
  <small>相關科目:<span id="relative-subjects"></span></small>
  <br>
  <br>
  <%= f.input :visible, collection: [ "免費可見", "購點後可見", "付費可見"], :label => "可見性設定", :include_blank => false %>
  <%= f.input :public_date,as: :string, input_html: {type: :date}, label: '上架日期' %>
  <%= f.input :note, label: '備註' %>
  <% if paper.active != nil %>
  <%= f.input :active,:item_wrapper_class => 'inline', as: :radio_buttons, label: '有效性' %>
  <% else %>
  <%= f.input :active,:item_wrapper_class => 'inline',:checked => ['無效', false], as: :radio_buttons, label: '有效性' %>
  <% end %>
  <%= f.button :submit , "送出", class: "btn btn-primary" %>
  <a href="/papers"><button class= "btn btn-primary">上一頁</button></a>
  <% if paper.title != nil %> 
  <button class="btn btn-success"><%= link_to "題目管理", paper_questions_path(paper,:paper_id => paper.id) %></button>
  <% end %>
<% end %>
<script type="text/javascript" src="/js/getSubjects.js" defer></script>

app/views/papers/edit.html.erb
<h1>編輯試卷</h1>

<%= render 'form', paper: @paper %>

app/views/papers/index.html.erb
<script>
$(function(){
  $("#batch-active").click(function(){
    var paper_ids = [];
    var active = true;
    var count = 0;
    $(".paper_id:checked").each(function(){
      paper_ids.push($(this).val());
    });
    ajaxBatchUpdate(paper_ids,active,count)
  });
  $("#batch-inactive").click(function(){
    var paper_ids = [];
    var active = false;
    var count = 0;
    $(".paper_id:checked").each(function(){
      paper_ids.push($(this).val());
    });
    ajaxBatchUpdate(paper_ids,active,count)
  });
  $("#check-all").click(function(){
    $(".paper_id").each(function(){
      $(this).attr("checked","checked")
    });
  })
  function ajaxBatchUpdate(paper_ids,active,count){
    $.ajax({
        type: "POST",
        url: "/papers/"+paper_ids[count],
        dataType: "script",
        contentType: 'application/json',
        data: JSON.stringify({ active:active, _method:'put' })
        })
        .complete(function(data){
          if(count< paper_ids.length-1){
            count += 1;
            ajaxBatchUpdate(paper_ids,active,count);
          }
        })
  }
})

</script> 

<p id="notice"><%= notice %></p>

<h1>試卷管理</h1>
<button class="btn btn-primary"><%= link_to '新增試卷', new_paper_path %></button>
<button class="btn btn-success" id="batch-active">批次有效</button>
<button class="btn btn-danger" id="batch-inactive">批次無效</button>
<%= render 'filters', paper: @paper %>
<table class="table">
  <thead>
    <tr class="thead">
      <th><button class="btn btn-info" id="check-all">全選</button></th>
      <th>Id</th>
      <th>試卷科目&nbsp;
        <a class="sorter" id="name-ASC" href="/papers?relation=paper_subjects&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/papers?relation=paper_subjects&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th>年級&nbsp;
        <a class="sorter" id="name-ASC" href="/papers?relation=grades&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/papers?relation=grades&&order=DESC"><img src="/sort-down.png"></a>      
      </th>      
      <th>試卷名稱&nbsp;
        <a class="sorter" id="name-ASC" href="/papers?orderParam=title&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/papers?orderParam=title&&order=DESC"><img src="/sort-down.png"></a>
      </th>
      <th>可見性設定&nbsp;
        <a class="sorter" id="name-ASC" href="/papers?orderParam=visible&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/papers?orderParam=visible&&order=DESC"><img src="/sort-down.png"></a>         
      </th>
      <th>上架日期&nbsp;
        <a class="sorter" id="name-ASC" href="/papers?orderParam=public_date&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/papers?orderParam=public_date&&order=DESC"><img src="/sort-down.png"></a>      
      </th>
      <th>備註&nbsp;
        <a class="sorter" id="name-ASC" href="/papers?orderParam=note&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/papers?orderParam=note&&order=DESC"><img src="/sort-down.png"></a>        
      </th>
      <th>有效性&nbsp;
        <a class="sorter" id="name-ASC" href="/papers?orderParam=active&&order=ASC"><img src="/sort-up.png"></a>
        <a class="sorter" id='name-DESC' href="/papers?orderParam=active&&order=DESC"><img src="/sort-down.png"></a>       
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><input type="checkbox" class="paper_id" value=<%= paper.id %>></td>
        <td><%= paper.id %></td>
        <% if paper.paper_subject!=nil%>
          <td class="column-name"><%= paper.paper_subject.title %></td>
        <% end %>
        <td><span class="column-name">
        <% paper.grades.each do |g| %>
          <%= g.name %>,
        <% end %>
        </span></td>
        <td class="column-name"><%= paper.title %></td>
        <td class="column-name"><%= paper.visible %></td>
        <td class="column-name"><%= paper.public_date %></td>
        <td class="column-name"><%= paper.note %></td>
        <td>
        <% if paper.active == true%>
        <span class="active">已啟用</span>
        <% else %>
        <span class="inactive">未啟用</span>
        <% end %>
        </td>
        <td><%= link_to '編輯', edit_paper_path(paper) %></td>
        <td><%= link_to '刪除', paper, method: :delete, data: { confirm: '你確定?' } %></td>
        <td><%= link_to "題目管理", paper_questions_path(paper,:paper_id => paper.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @papers, :previous_label => '上一頁', :next_label => '下一頁' %>

app/views/papers/new.html.erb
<h1>新增試卷</h1>

<%= render 'form', paper: @paper %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Active:</strong>
  <%= @paper.active %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @paper.visible %>
</p>

<p>
  <strong>Public date:</strong>
  <%= @paper.public_date %>
</p>

<p>
  <strong>Note:</strong>
  <%= @paper.note %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @paper.grade %>
</p>

<p>
  <strong>Open count:</strong>
  <%= @paper.open_count %>
</p>

<p>
  <strong>Correct count:</strong>
  <%= @paper.correct_count %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>